spring:
   batch:
      job:
         enabled: false
   jackson:
      serialization.indent_output: true
      time-zone: GMT+8
   datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:oracle:thin:@47.96.118.135:1521:S460
      username: faext
      password: faext
      hikari:
         data-source-properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
         minimum-idle: 2
         maximum-pool-size: 15
         connection-test-query: SELECT 1 FROM DUAL
         idle-timeout: 10000
         connection-timeout: 30000
         
# Mybatis 相关配置
mybatis:
    mapperLocations: classpath*:mapper/*.xml
    config: classpath:config/mybatis-config.xml
    
server:
    port: 8024
    tomcat:
        max-threads: 200

logging:
   level:
      com:
         sxd:
            swapping:
               dao:
                  mybatis: debug
